name: build

on: push

env:
  IMAGE_FQDN: ghcr.io/eugenmayer/ldaptestserver

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Generate certificates
        run: cd tls && ./generate-certs.sh ldap no
      # push only on main
      - name: Build type1
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_FQDN }}:bitnami-type1
            ${{ env.IMAGE_FQDN }}:bitnami-type1-${{ github.ref_name }}
          build-args: |
            TEMPLATE_PATH=./ldif/bootstrap/bitnami/data-template-type1-static.ldif
            LDAP_ROOT=dc=example,dc=org
      - name: Build type2
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_FQDN }}:bitnami-type2
            ${{ env.IMAGE_FQDN }}:bitnami-type2-${{ github.ref_name }}
          build-args: |
            TEMPLATE_PATH=./ldif/bootstrap/bitnami//data-template-type2-static.ldif
            LDAP_ROOT=dc=kontextwork-test,dc=de
